# Generated by Django 3.2.4 on 2025-07-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver', '0047_auto_20220620_1153'),
    ]

    operations = [

        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['reference'], name='silver_subs_referen_d59898_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['uuid'], name='silver_tran_uuid_3a6529_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['external_reference'], name='silver_tran_externa_b33c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='silver_tran_created_6db089_idx'),
        ),
    ]
